package network

var (
	goldenVersions = []byte(`[
		{
		   "chain_name":"TEZOS_MAINNET",
		   "distributed_db_version":0,
		   "p2p_version":0
		}
	 ]`)

	goldenConstants = []byte(`{
		"proof_of_work_nonce_size":8,
		"nonce_length":32,
		"max_revelations_per_block":32,
		"max_operation_data_length":16384,
		"max_proposals_per_delegate":20,
		"preserved_cycles":3,
		"blocks_per_cycle":2048,
		"blocks_per_commitment":32,
		"blocks_per_roll_snapshot":256,
		"blocks_per_voting_period":8192,
		"time_between_blocks":[
		   "30",
		   "40"
		],
		"endorsers_per_block":32,
		"hard_gas_limit_per_operation":"400000",
		"hard_gas_limit_per_block":"4000000",
		"proof_of_work_threshold":"70368744177663",
		"tokens_per_roll":"10000000000",
		"michelson_maximum_type_size":1000,
		"seed_nonce_revelation_tip":"125000",
		"origination_size":257,
		"block_security_deposit":"32000000",
		"endorsement_security_deposit":"4000000",
		"block_reward":"0",
		"endorsement_reward":"0",
		"cost_per_byte":"1000",
		"hard_storage_limit_per_operation":"60000"
	 }`)

	goldenChainID = []byte(`"NetXgtSLGNJvNye"`)

	goldenConnections = []byte(`[
		{
		   "incoming":false,
		   "peer_id":"idtf1oEMHiAfddScGyaYqoMMi1u6P7",
		   "id_point":{
			  "addr":"::ffff:91.225.238.250",
			  "port":9732
		   },
		   "remote_socket_port":9732,
		   "versions":[
			  {
				 "name":"TEZOS_ALPHANET_2018-11-30T15:30:56Z",
				 "major":0,
				 "minor":0
			  },
			  {
				 "name":"TEZOS_ALPHANET_2018-11-30T15:30:56Z",
				 "major":0,
				 "minor":0
			  }
		   ],
		   "private":false,
		   "local_metadata":{
			  "disable_mempool":false,
			  "private_node":false
		   },
		   "remote_metadata":{
			  "disable_mempool":false,
			  "private_node":false
		   }
		},
		{
		   "incoming":false,
		   "peer_id":"idsohLhiCYYWrw9FwGL4i5Z4kZ8oLr",
		   "id_point":{
			  "addr":"::ffff:34.255.45.149",
			  "port":9732
		   },
		   "remote_socket_port":9732,
		   "versions":[
			  {
				 "name":"TEZOS_ALPHANET_2018-11-30T15:30:56Z",
				 "major":0,
				 "minor":0
			  },
			  {
				 "name":"TEZOS_ALPHANET_2018-11-30T15:30:56Z",
				 "major":0,
				 "minor":0
			  }
		   ],
		   "private":false,
		   "local_metadata":{
			  "disable_mempool":false,
			  "private_node":false
		   },
		   "remote_metadata":{
			  "disable_mempool":false,
			  "private_node":false
		   }
		},
		{
		   "incoming":false,
		   "peer_id":"idse7w6uFyRyaM2DLVwLs4hZ6XNKL6",
		   "id_point":{
			  "addr":"::ffff:34.255.45.196",
			  "port":9732
		   },
		   "remote_socket_port":9732,
		   "versions":[
			  {
				 "name":"TEZOS_ALPHANET_2018-11-30T15:30:56Z",
				 "major":0,
				 "minor":0
			  },
			  {
				 "name":"TEZOS_ALPHANET_2018-11-30T15:30:56Z",
				 "major":0,
				 "minor":0
			  }
		   ],
		   "private":false,
		   "local_metadata":{
			  "disable_mempool":false,
			  "private_node":false
		   },
		   "remote_metadata":{
			  "disable_mempool":false,
			  "private_node":false
		   }
		},
		{
		   "incoming":false,
		   "peer_id":"idrm1KhfdmV9pq2jvCnWaGYppN6QAT",
		   "id_point":{
			  "addr":"::ffff:34.249.109.84",
			  "port":9732
		   },
		   "remote_socket_port":9732,
		   "versions":[
			  {
				 "name":"TEZOS_ALPHANET_2018-11-30T15:30:56Z",
				 "major":0,
				 "minor":0
			  },
			  {
				 "name":"TEZOS_ALPHANET_2018-11-30T15:30:56Z",
				 "major":0,
				 "minor":0
			  }
		   ],
		   "private":false,
		   "local_metadata":{
			  "disable_mempool":false,
			  "private_node":false
		   },
		   "remote_metadata":{
			  "disable_mempool":false,
			  "private_node":false
		   }
		},
		{
		   "incoming":false,
		   "peer_id":"idr2piupJd1ru7zpHPKbu8f8ADqf3H",
		   "id_point":{
			  "addr":"::ffff:34.253.64.43",
			  "port":9732
		   },
		   "remote_socket_port":9732,
		   "versions":[
			  {
				 "name":"TEZOS_ALPHANET_2018-11-30T15:30:56Z",
				 "major":0,
				 "minor":0
			  },
			  {
				 "name":"TEZOS_ALPHANET_2018-11-30T15:30:56Z",
				 "major":0,
				 "minor":0
			  }
		   ],
		   "private":false,
		   "local_metadata":{
			  "disable_mempool":false,
			  "private_node":false
		   },
		   "remote_metadata":{
			  "disable_mempool":false,
			  "private_node":false
		   }
		},
		{
		   "incoming":false,
		   "peer_id":"idtdNBn7HYqMibrFRF8TPsquem4GEb",
		   "id_point":{
			  "addr":"::ffff:52.50.125.15",
			  "port":9732
		   },
		   "remote_socket_port":9732,
		   "versions":[
			  {
				 "name":"TEZOS_ALPHANET_2018-11-30T15:30:56Z",
				 "major":0,
				 "minor":0
			  },
			  {
				 "name":"TEZOS_ALPHANET_2018-11-30T15:30:56Z",
				 "major":0,
				 "minor":0
			  }
		   ],
		   "private":false,
		   "local_metadata":{
			  "disable_mempool":false,
			  "private_node":false
		   },
		   "remote_metadata":{
			  "disable_mempool":false,
			  "private_node":false
		   }
		}
	 ]`)
)

type client struct {
	ReturnBody []byte
}

func (c *client) Post(path, args string) ([]byte, error) {
	return c.ReturnBody, nil
}

func (c *client) Get(path string, params map[string]string) ([]byte, error) {
	return c.ReturnBody, nil
}
